spring.application.name=evaluation
# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/hire_track?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Jeno@2429

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl_auto=update
spring.main.allow-circular-references=true